export default {
    //Account
    Main: "Main",
    ConfirmTrans: "ConfirmTrans",
    Home: "Home",
    Welcome: "Welcome",
    AccountHome: "AccountHome",
    AccountLogin: "AccountLogin",
    AccountPromotion: "AccountPromotion",
    AccountEditProfile: "AccountEditProfile",
    AccountChangePassword: "AccountChangePassword",
    AccountRegistry: "AccountRegistry",
    AccountProfile: "AccountProfile",
    AccountNotification: "AccountNotification",
    AccountTransHis: "AccountTransHis",
    AccountTransHisDetail: "AccountTransHisDetail",
    ScanQR: "ScanQR",
    PaymentScanQR: "PaymentScanQR",
    WalletDeposit: "WalletDeposit",
    WalletTransfer: "WalletTransfer",
    WalletTransferInfo: "WalletTransferInfo",
    Hot: "Hot",
    PayInfo: "PayInfoBK",
    MyQRCode: 'MyQRCode',
    Setting: 'Setting',
    PaymentCode: 'PaymentCode',
    PayInfoByCode: 'PayInfoByCode',
    AccManager: 'AccManager',
    AccInfo: 'AccInfo',
}
